
//this function returns an array of length 1 with an object containing user information generated by an api
//allows for testing with uniqe user information
//use getUserFromWeb().then((val) => setName(val.name.first));
//TODO: repace with our own backend
export const getUserFromWeb = () => {
    return fetch('https://randomuser.me/api/?results='+1)
      .then((response) => response.json())
      .then((json) => {
        console.log(json.results)
        //setName(json.results[0].name.first)
        //this.state = ;
        return json.results[0];
      })
      .catch((error) => {
        console.error(error);
      });
  }